version: '3'

services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: always

  scrapy_project:
    build: .
    depends_on:
      - mongo
    links:
      - mongo
  
  flask:
    build: ./app
    ports:
      - "5000:5000"
    depends_on:
      - mongo

